Adding flexbox template
houdamzari/Portfolio-Website pull request #1
Opened 2022-10-26 16:12 UTC by houdamzari

- Setting up linters
- Setting up flexbox for section 1 and 2
- Adding CSS to the elements 
- Fixing responsive view issues

2022-10-26 16:58 UTC, fobadara requested changes
# REQUIRES CHANGES ♻️ 
Hi @houdamzari, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Linters are set up correctly and passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 16:58 UTC, fobadara commented on index.html
> +    </section>
[REQUIRED] This should be a `header` tag instead of section.

2022-10-26 16:58 UTC, fobadara commented on index.html
> +        <div class="logo">My logo</div>
[REQUIRED] This should be wrapped in an `anchor` tag

2022-10-26 16:58 UTC, fobadara commented on index.html
> +          me.
[REQUIRED] This should be a `p` tag.

2022-10-26 16:58 UTC, fobadara commented on index.html
> +      </div>
[REQUIRED] Kindly wrap these icons in `ul` and `li` tags

2022-10-26 16:58 UTC, fobadara commented on index.html
> +          me.
[REQUIRED] Your elements are overflowing. Kindly fix it

![houdamzari1](https://user-images.githubusercontent.com/62938735/198087977-19706e41-f878-4031-b925-9cccb2ba7b53.gif)

2022-10-26 16:58 UTC, fobadara commented on index.html
> +        <div class="hamburger-menu">
[REQUIRED] Kindly wrap each navigation with an anchor tag

2022-10-27 09:34 UTC, leonardodiasb approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @houdamzari 🔥 

You worked hard in all the instructions that the previous Code Reviewers give you👍🏽 

Now you can merge this branch 🚀 

## Highlights

✅ Linters are set up correctly and passing

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 09:47 UTC, merged