Adding project section
houdamzari/Portfolio-Website pull request #3
Opened 2022-10-27 18:48 UTC by houdamzari

- Added Grid Layout 
- Added Flexbox to align the cards.
- Used lists on navigation links .
- Implemented buttons interactions ( on hover, on press )

2022-10-27 19:18 UTC, Lizdev-05 requested changes
Hi <STUDENT_MENTION>, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there-reach](https://user-images.githubusercontent.com/73854999/198377006-021e7bef-216b-48d3-b788-94c84a172547.gif)

## Highlights
- Correct GitHub Flow 👍🏾
- Good commit history 🥇
- Good PR title/description 💯
- All linters passed 🥇
- Personalized README file ✔

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

You can also consider the following:
- Before submitting your work for review in future projects, kindly close unused pull requests to avoid confusion.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 19:18 UTC, Lizdev-05 commented on index.html
> +          </div>
Good job so far @houdamzari☺, kindly wrap the technologies in this section i.e **JavaScript, CSS, and Html** inside of the `ul` tag in accordance with the requirement.

2022-10-27 19:18 UTC, Lizdev-05 commented on index.html
> +      <div class="links-text">Let's connect</div>
You have a great and neat code here 👍, but Kindly wrap 'Let's connect' inside a `header` tag to improve the scalability of your code.

2022-10-28 07:59 UTC, sumairq approved these changes
### Hi @houdamzari , 

<img src="https://media4.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 08:09 UTC, merged