Contact form
houdamzari/Portfolio-Website pull request #7
Opened 2022-11-01 14:28 UTC by houdamzari

- Added contact form 
- Added validation rules to the form
- Setup Formspree

2022-11-01 14:48 UTC, Olamarx requested changes
Hi @houdamzari && @Lucash2022, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

## Highlights
- All linters passed ✔️ 
- Form works as required ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-01 14:48 UTC, Olamarx commented on index.html
> +          <button type="submit" class="form_button">Get in Touch</button>
- [ ] Kindly add the button interaction in terms of hover and others just as on the Figma template
![image](https://user-images.githubusercontent.com/86200356/199261124-787e07d7-7bbc-463d-a87e-8146ef43daa3.png)

2022-11-01 14:48 UTC, Olamarx requested changes
Hi @houdamzari && @Lucash2022, 

Good job so far, indeed you have spent time on this project!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/hXz6GN0ZilLwhgLo49/giphy.gif"/>

## Highlights
- All linters passed ✔️ 
- Form works as required ✅ 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 07:19 UTC, leehaney254 commented
Your commits are professional and descriptive. Nice work :smile:

2022-11-02 07:26 UTC, Talha-Hanif5666 reviewed
**Hello @Lucash2022** 
![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966](https://user-images.githubusercontent.com/114238556/199425638-3569ddfd-0bb6-4db4-8d60-2199464d8f17.gif)

**Highlights**
Great job setting up the correct linters :heavy_check_mark: 
Professional documentation :heavy_check_mark: 
Correct workflow :heavy_check_mark: 
Meaningful commit messages :heavy_check_mark: 

There are some issues that you still need to work on to go to the next project but you are almost there!


**#Changes Required :recycle: 
Nice work and you did it so well :+1:** 
I have leave a comment that want changes, Kindly please see my comment and change the code according to it. Thank You 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

**Cheers and Happy coding! partying_face clapclap**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

2022-11-02 07:26 UTC, Talha-Hanif5666 commented on index.html
> -              <input type="text" placeholder="Name" class="form_input" maxlength="30" required class="form_input">
Nice work though, but i think it is better not to leave any blank lines in your code where unnecessary.  Doing this your code looks your code unclear.
Kindly please remove that blank line. Thank you

2022-11-02 07:43 UTC, Bondok6 approved these changes
# STATUS: APPROVED :green_circle: :clap: 

## Hi @houdamzari  and @Lucash2022 🙋‍♂️, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Great job Implementing the changes provided by the previous reviewers ✅
- Your project is professional ✅
- Your repo is professional ✅
- Well structured files ✅
- No Linter errors ✅


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

<img src="https://camo.githubusercontent.com/54a5d803a138b5a1a1242a607e4c1192c852cab8c591c1ddcaa33d06b51560f6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f686c516559335062684833692f67697068792e676966" />


## Optional suggestions

- [OPTIONAL] I suggest adding the `MIT.md` file to your project 👌, Here is the [Micorverse Template](https://github.com/microverseinc/readme-template/blob/master/MIT.md), and remember to customize it 😉

> The MIT license gives users express permission to reuse code for any purpose, sometimes even if the code is part of proprietary software. As long as users include the original copy of the MIT license in their distribution, they can make any changes or modifications to the code to suit their own needs. 💯

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-02 07:43 UTC, Bondok6 commented on index.html
> +            <p class="contact_paragraph">If you have an application you are interested in developing, a feature that you need built or a project that needs coding. I’d love to help with it </p>
- [OPTIONAL]  I suggest removing the `<h1>` tag from here and adding another hx (`<h2>`, `<h3>`, ....) 👌 . to Follow best practices for HTML **Only Use H1 Elements Once Per Page for optimal SEO**. 
for more info, you can check this [Link](https://techstacker.com/seo-only-use-h1-elements-once-per-page/). 💡

2022-11-02 13:54 UTC, merged